# Generated by Django 5.2 on 2025-04-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_rename_medical_history_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
